/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_androiddev_nativelog_loglib_NativeLogLib */

#ifndef _Included_com_androiddev_nativelog_loglib_NativeLogLib
#define _Included_com_androiddev_nativelog_loglib_NativeLogLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androiddev_nativelog_loglib_NativeLogLib
 * Method:    LibMain
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androiddev_nativelog_loglib_NativeLogLib_LibMain
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_androiddev_nativelog_loglib_NativeLogLib
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androiddev_nativelog_loglib_NativeLogLib_getNativeString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
