/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_androiddev_hellondk_NativeLib */

#ifndef _Included_com_intel_androiddev_hellondk_NativeLib
#define _Included_com_intel_androiddev_hellondk_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_androiddev_hellondk_NativeLib
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_androiddev_hellondk_NativeLib_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
